# Generated by Django 5.0.1 on 2024-01-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_postcode_event_image'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organization',
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ManyToManyField(null=True, to='organization.organization'),
        ),
    ]
