# Generated by Django 5.0.1 on 2024-01-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_organization_event_organization'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organization',
            field=models.ManyToManyField(to='organization.organization'),
        ),
    ]
