version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000